# Generated by Django 4.0.2 on 2022-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_stepprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='challenge_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('challenge', 'order'), name='step_unique'),
        ),
        migrations.AddConstraint(
            model_name='step',
            constraint=models.UniqueConstraint(fields=('challenge', 'title'), name='step_title_unique'),
        ),
        migrations.AddConstraint(
            model_name='stepprogress',
            constraint=models.UniqueConstraint(fields=('user', 'step'), name='progress_step_user_unique'),
        ),
    ]
