# Generated by Django 4.0.2 on 2022-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_step_order_challenge_challenge_title_unique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='challenge',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='challenge_order_unique'),
        ),
    ]
